# Generated by Django 2.2.5 on 2020-01-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiTestName', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('apiTestdesc', models.CharField(max_length=200, verbose_name='描述')),
                ('apiTester', models.CharField(max_length=200, verbose_name='测试负责人')),
                ('apiTestResult', models.BooleanField(verbose_name='测试结果')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiName', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apiUrl', models.CharField(max_length=200, verbose_name='url地址')),
                ('apiStep', models.CharField(max_length=100, null=True, verbose_name='测试步骤')),
                ('apiParamValue', models.CharField(max_length=800, verbose_name='请求参数')),
                ('apiMethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('apiResult', models.CharField(max_length=200, verbose_name='预测结果')),
                ('apiRespose', models.CharField(max_length=5000, null=200, verbose_name='响应数据')),
                ('apiStatus', models.BooleanField(verbose_name='是否通过')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('apiTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Apitest')),
            ],
        ),
    ]
